version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - dataplatform-network

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - dataplatform-network

  proxy:
      container_name: proxy
      build: ./proxy
      ports:
        - 8000:8000
      depends_on:
        - redis
      links:
        - redis
      networks:
        - dataplatform-network
volumes:
  mongo-data:
    driver: local


networks:
  dataplatform-network:
    name: dataplatform-network
    driver: bridge
